SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH, U.GENDER, COUNT(DISTINCT U.USER_ID) AS USERS
FROM USER_INFO U
    JOIN ONLINE_SALE O
    ON U.USER_ID=O.USER_ID
GROUP BY YEAR, MONTH, U.GENDER
HAVING (U.GENDER IS NOT NULL)
ORDER BY YEAR, MONTH, GENDER