Select FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
From  REST_INFO
Where (FOOD_TYPE, FAVORITES) In (Select FOOD_TYPE, Max(FAVORITES) From REST_INFO R Group by FOOD_TYPE )
Group by FOOD_TYPE
Order by FOOD_TYPE Desc
