SELECT CATEGORY, PRICE AS MAX_PRICE, PRODUCT_NAME
FROM FOOD_PRODUCT
WHERE PRICE IN (SELECT MAX(PRICE) FROM FOOD_PRODUCT GROUP BY CATEGORY)
    AND CATEGORY IN ('과자', '국', '김치', '식용유') 
ORDER BY MAX_PRICE DESC

# SELECT *
# FROM FOOD_PRODUCT
# WHERE CATEGORY LIKE '과자' 
#     OR CATEGORY LIKE '국' 
#     OR CATEGORY LIKE '김치'
#     OR CATEGORY LIKE '식용유'