# Select MEMBER_ID, MEMBER_NAME, GENDER, DATE_FORMAT(DATE_OF_BIRTH, '%Y-%m-%d') DATE_OF_BIRTH
# From MEMBER_PROFILE 
# Where (TLNO Is Not Null) And (Month(DATE_OF_BIRTH)='3') And Gender='W'
# Order by MEMBER_ID


SELECT MEMBER_ID, MEMBER_NAME, GENDER, DATE_FORMAT(DATE_OF_BIRTH, '%Y-%m-%d') AS DATE_OF_BIRTH
FROM MEMBER_PROFILE
WHERE MONTH(DATE_OF_BIRTH)='3' AND GENDER='W' AND TLNO IS NOT NULL