SELECT O.PRODUCT_ID, P.PRODUCT_NAME, SUM(P.PRICE*O.AMOUNT) AS TOTAL_SALES 
FROM FOOD_PRODUCT P
    JOIN FOOD_ORDER O
    ON P.PRODUCT_ID=O.PRODUCT_ID
WHERE DATE_FORMAT(O.PRODUCE_DATE, '%Y-%m') LIKE '2022-05%'
GROUP BY O.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, O.PRODUCT_ID

# SELECT *
# FROM FOOD_ORDER
# WHERE DATE_FORMAT(PRODUCE_DATE, '%Y-%m') LIKE '2022-05%'