SELECT I.REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, ROUND(AVG(R.REVIEW_SCORE), 2) AS SCORE
FROM REST_INFO I, REST_REVIEW R
WHERE I.REST_ID=R.REST_ID
GROUP BY R.REST_ID
HAVING ADDRESS LIKE '서울%'
ORDER BY SCORE DESC, FAVORITES DESC

# SELECT *
# FROM REST_INFO I, REST_REVIEW R
# WHERE I.REST_ID=R.REST_ID AND ADDRESS LIKE '%서울%'
